dist: trusty
sudo: required
language: c

before_install:
  - wget https://haskell.org/platform/download/8.0.2/haskell-platform-8.0.2-unknown-posix--minimal-x86_64.tar.gz
  - tar -xzvf ./haskell-platform-8.0.2-unknown-posix--minimal-x86_64.tar.gz
  - sudo ./install-haskell-platform.sh
  - cabal update && cabal install hlint hpc-coveralls

script:
  - ~/.cabal/bin/hlint .
  - cabal install --dependencies-only --enable-tests
  - cabal configure --enable-tests --enable-coverage --enable-library-coverage
  - cabal build
  - cabal test --show-details=always

after_script:
  - ~/.cabal/bin/hpc-coveralls --display-report tests

notifications:
  email:
    on_failure: change
    on_success: change
