#!/bin/bash

if [ -z "$TRAVIS_JOB_ID" ]; then
    exit 0
fi

if [ -z "$(which hpc-coveralls)" ]; then
    echo "hpc-coveralls not found in $PATH - install it"
    exit 1
else
    hpc-coveralls --display-report tests
fi
